services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  node-func1:
    build:
      context: ./func1
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  node-func2:
    build:
      context: ./func2
      dockerfile: Dockerfile
    ports:
      - "3002:3000"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
