global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'funciones'
    static_configs:
      - targets: ['node-func1:3000', 'node-func2:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
